{application,combine,
             [{registered,[]},
              {description,"A parser combinator library for Elixir projects."},
              {applications,[kernel,stdlib,elixir]},
              {vsn,"0.6.0"},
              {modules,['Elixir.Combine','Elixir.Combine.Helpers',
                        'Elixir.Combine.ParserState',
                        'Elixir.Combine.Parsers.Base',
                        'Elixir.Combine.Parsers.Binary',
                        'Elixir.Combine.Parsers.Text']}]}.